fix "NameError: name 'unicode' is not defined"
error happens while running `./makecrx.sh`
because python is python3 on some systems
and python 3 renamed the `unicode` type to `str`,
the old `str` type has been replaced by `bytes`.

Removing whitespaces and comments...
Traceback (most recent call last):
  File "./utils/merge-rulesets.py", line 77, in <module>
    for rfile in sorted(xml_ruleset_files):
  File "./utils/merge-rulesets.py", line 25, in normalize
    f = unicodedata.normalize('NFC', unicode(f, 'utf-8')).encode('utf-8')
NameError: name 'unicode' is not defined